import os
import tempfile
from fpdf import FPDF


def clean_text(text):
    if not isinstance(text, str):
        text = str(text)
    # Remove special characters that break PDF
    text = text.replace('\u2019', "'").replace('\u2018', "'")
    text = text.replace('\u201c', '"').replace('\u201d', '"')
    text = text.replace('\u2013', '-').replace('\u2014', '-')
    text = text.replace('\u2022', '*').replace('\u00b0', ' degrees')
    return text.encode('latin-1', 'replace').decode('latin-1')


def safe_cell(pdf, text, size=9, bold=False):
    style = "B" if bold else ""
    pdf.set_font("Helvetica", style, size)
    # Use cell instead of multi_cell for single lines
    safe = clean_text(str(text))[:100]
    pdf.cell(0, 6, safe, ln=True)


def safe_multi(pdf, text, size=9):
    pdf.set_font("Helvetica", "", size)
    safe = clean_text(str(text))
    # Split into chunks of 90 chars max per line
    words = safe.split(' ')
    line = ""
    for word in words:
        if len(line) + len(word) + 1 < 90:
            line += word + " "
        else:
            if line.strip():
                pdf.cell(0, 5, line.strip(), ln=True)
            line = word + " "
    if line.strip():
        pdf.cell(0, 5, line.strip(), ln=True)


def section(pdf, title):
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(46, 117, 182)
    pdf.cell(0, 8, clean_text(title), ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(50, 50, 50)
    pdf.ln(2)


def generate_summary(df, llm):
    col_info = ", ".join(
        [f"{col} ({str(df[col].dtype)})" for col in df.columns])
    prompt = (
        "You are a data analyst. Write a 5 sentence summary about this dataset.\n"
        "Columns: " + col_info + "\n"
        "Rows: " + str(len(df)) + "\n\n"
        "Rules:\n"
        "- Use only plain English\n"
        "- No bullet points\n"
        "- No special characters\n"
        "- No markdown\n"
        "- Maximum 5 sentences"
    )
    response = llm.invoke(prompt)
    return response.content.strip()


def generate_pdf_report(df, chat_history, summary, figures):
    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title ─────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(31, 56, 100)
    pdf.cell(0, 12, "AI SQL Data Analyst Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, "Generated by AI SQL Analyst", ln=True, align="C")
    pdf.ln(6)

    # ── 1. Overview ───────────────────────────────────────
    section(pdf, "1. Dataset Overview")
    safe_cell(pdf, f"Total Rows: {len(df):,}")
    safe_cell(pdf, f"Total Columns: {len(df.columns)}")
    pdf.ln(2)
    safe_cell(pdf, "Columns:", bold=True)
    for col in df.columns:
        safe_cell(pdf, f"  {col} — {str(df[col].dtype)}")
    pdf.ln(4)

    # ── 2. AI Summary ─────────────────────────────────────
    section(pdf, "2. AI Generated Summary")
    safe_multi(pdf, summary)
    pdf.ln(4)

    # ── 3. Key Statistics ─────────────────────────────────
    section(pdf, "3. Key Statistics")
    try:
        num_cols = df.select_dtypes(include='number').columns.tolist()
        if num_cols:
            for col in num_cols[:8]:
                col_data = df[col].dropna()
                if len(col_data) > 0:
                    line = (
                        f"{col}:  "
                        f"Min={round(float(col_data.min()), 2)}  "
                        f"Max={round(float(col_data.max()), 2)}  "
                        f"Mean={round(float(col_data.mean()), 2)}  "
                        f"Nulls={int(df[col].isnull().sum())}"
                    )
                    safe_cell(pdf, line)
        else:
            safe_cell(pdf, "No numeric columns found.")
    except Exception as e:
        safe_cell(pdf, f"Stats error: {str(e)[:80]}")
    pdf.ln(4)

    # ── 4. Null Analysis ──────────────────────────────────
    section(pdf, "4. Null Value Analysis")
    try:
        total_nulls = int(df.isnull().sum().sum())
        safe_cell(pdf, f"Total null values in dataset: {total_nulls}")
        pdf.ln(1)
        for col in df.columns:
            count = int(df[col].isnull().sum())
            pct = round(count / len(df) * 100, 1)
            safe_cell(pdf, f"  {col}: {count} nulls ({pct}%)")
    except Exception as e:
        safe_cell(pdf, f"Error: {str(e)[:80]}")
    pdf.ln(4)

    # ── 5. Chat History ───────────────────────────────────
    section(pdf, "5. Questions and Answers")
    if chat_history:
        for i, chat in enumerate(chat_history, 1):
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(31, 56, 100)
            safe_multi(pdf, f"Q{i}: {str(chat['question'])[:200]}")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(50, 50, 50)
            safe_multi(pdf, f"Answer: {str(chat['answer'])[:400]}")
            if chat.get('sql') and not str(chat['sql']).startswith('--'):
                pdf.set_font("Courier", "", 7)
                pdf.set_text_color(100, 100, 100)
                safe_multi(pdf, f"SQL: {str(chat['sql'])[:200]}")
            pdf.set_text_color(50, 50, 50)
            pdf.ln(3)
    else:
        safe_cell(pdf, "No questions asked yet.")
    pdf.ln(4)

    # ── 6. Charts ─────────────────────────────────────────
    if figures:
        section(pdf, "6. Visualizations")
        for title, fig in figures:
            try:
                with tempfile.NamedTemporaryFile(
                        suffix=".png", delete=False) as tmp:
                    fig.write_image(
                        tmp.name,
                        width=500,
                        height=300,
                        scale=2
                    )
                    tmp_path = tmp.name
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(31, 56, 100)
                safe_cell(pdf, str(title)[:80], bold=True)
                pdf.image(tmp_path, w=150)
                pdf.ln(4)
                os.unlink(tmp_path)
            except Exception as e:
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(150, 0, 0)
                safe_cell(pdf, f"Chart error: {str(e)[:80]}")
                pdf.ln(2)

    return bytes(pdf.output())